[project]
name = "spotctl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "keyboard>=0.13.5",
    "pynput>=1.8.1",
    "spotipy>=2.25.1",
]
